### ISSUE TITLE
SigMakerEx: ** Gerneral C exception: run() ***

### ISSUE THREAD

**Issue by gurrenm3** [kweatherman/sigmakerex#8]
When I try to scan a function I get this error:
```
SigMakerEx: Finding function signature.
SigMakerEx: * InstToSig: Decode anomaly @ 0x000001401A560C! decodeSize: 9, itemSize: 52 *
 F: 20505C00, "FF_DWORD, FF_0OFF, FF_REF, FF_NAME, FF_DATA, FF_COMM"
 'mov     ds:0F3001A263E001A0Bh, eax; jump table for switch statement'

SigMakerEx: ** Gerneral C exception: run() ***
```

We have the PDB for this game, here is what it looks like:
```void __fastcall cGcApplicationDeathState::Update(cGcApplicationDeathState *this, float lfTimeStep)```

**Comment by gurrenm3** [comment]
This is what is at that location:
```
text:00000001401A560C A3 0B 1A 00 3E 26 1A 00 F3 2D+jpt_1401A0BA1   dd offset $LN25_0 - 140000000h
.text:00000001401A560C 1A 00 25 2E 1A 00 58 42 1A 00+                                        ; DATA XREF: cGcApplicationDeathState::Update(float)+207↑r
.text:00000001401A560C B2 3A 1A 00 B3 43 1A 00 AB 4E+                dd offset $LN55 - 140000000h ; jump table for switch statement
.text:00000001401A560C 1A 00 DC 4E 1A 00 9A 4F 1A 00+                dd offset $LN57 - 140000000h
.text:00000001401A560C 26 50 1A 00 44 3C 1A 00 69 4E+                dd offset $LN59 - 140000000h
.text:00000001401A560C 1A 00                                         dd offset $LN78 - 140000000h
.text:00000001401A560C                                               dd offset $LN64 - 140000000h
.text:00000001401A560C                                               dd offset $LN88 - 140000000h
.text:00000001401A560C                                               dd offset $LN104 - 140000000h
.text:00000001401A560C                                               dd offset $LN106 - 140000000h
.text:00000001401A560C                                               dd offset $LN110 - 140000000h
.text:00000001401A560C                                               dd offset $LN116 - 140000000h
.text:00000001401A560C                                               dd offset $LN74_0 - 140000000h
.text:00000001401A560C                                               dd offset $LN102 - 140000000h
.text:00000001401A560C                               ?Update@cGcApplicationDeathState@@EEAAXM@Z endp```

**Comment by gurrenm3** [comment]
Here is the actual switch statement:
```
.text:00000001401A0B55 83 F8 0C                                      cmp     eax, 0Ch        ; switch 13 cases
.text:00000001401A0B58 0F 87 87 49 00 00                             ja      def_1401A0BA1   ; jumptable 00000001401A0BA1 default case
.text:00000001401A0B5E
.text:00000001401A0B5E                               loc_1401A0B5E:                          ; DATA XREF: .rdata:0000000142AFC040↓o
.text:00000001401A0B5E                                                                       ; .rdata:0000000142AFC058↓o ...
.text:00000001401A0B5E 48 89 9C 24 48 0B 00 00                       mov     [rsp+0B70h+var_28], rbx
.text:00000001401A0B66 48 8D 0D 93 F4 E5 FF                          lea     rcx, cs:140000000h
.text:00000001401A0B6D 4C 89 A4 24 40 0B 00 00                       mov     [rsp+0B70h+var_30], r12
.text:00000001401A0B75 0F 29 B4 24 20 0B 00 00                       movaps  [rsp+0B70h+var_50], xmm6
.text:00000001401A0B7D 0F 29 BC 24 10 0B 00 00                       movaps  [rsp+0B70h+var_60], xmm7
.text:00000001401A0B85 44 0F 29 84 24 00 0B 00 00                    movaps  [rsp+0B70h+var_70], xmm8
.text:00000001401A0B8E 44 0F 29 8C 24 F0 0A 00 00                    movaps  [rsp+0B70h+var_80], xmm9
.text:00000001401A0B97 8B 84 81 0C 56 1A 00                          mov     eax, ds:(jpt_1401A0BA1 - 140000000h)[rcx+rax*4]
.text:00000001401A0B9E 48 03 C1                                      add     rax, rcx
.text:00000001401A0BA1 FF E0                                         jmp     rax             ; switch jump
```

**Comment by gurrenm3** [comment]
Since I originally posted I've gotten 2 more ``SigMakerEx: ** Gerneral C exception: run() ***`` errors. The other 2 didn't give any extra info other than that. All 3 were somewhat fairly functions with the shortest being 775 lines in C pseudo-code mode. Also, I realize i didn't mention this earlier but this game is 64bit not 32 bit

**Comment by kweatherman** [comment]
Yea don't know how the instruction iterator ended up trying to decode that data.
`text:00000001401A560C A3 0B 1A 00 3E 26 1A 00 F3 2D+jpt_1401A0BA1   dd offset $LN25_0 - 140000000h`
Yea that whole block as an item is 52 bytes (13 x sizeof(DWORD)).

What "Create signature:" option, "Function"?

**Comment by kweatherman** [comment]
Okay. From the listing it doesn't look like it. But there is no junk code in these, like code from a VM packer?

**Comment by gurrenm3** [comment]
Essentially yeah. I cloned your repo and am using it to create a pattern for every named function in the database (about 85k). It's just the find function code in a loop over all functions

**Comment by gurrenm3** [comment]
Idk if it helps but it seems to happen every 5-6k functions. Also when I try to go to the specific broken one and use FindFunction on just that one it still doesn't work even after restarting IDA

**Comment by kweatherman** [comment]
Okay cool you automated it then.
And it ends up being sort of a stress test for the function analyzer.

Are you doing this to make some type of diffing or matching up tool?
I've actually made something similar but it works by making hashes of all functions (instead of using signatures).

So they do have junk code in them, or are they fragmented (for lack of a better term) where blocks in the function have gaps and jump over other functions or data?

**Comment by kweatherman** [comment]
Well, hashes are similar and they take a lot less space since they are typically just 8 bytes per hash. Depending on the hash type.
I used 64 bit hashes so there is a small chance of collisions. Assuming the function is unique.

It's a loaded subject about binary diffing. Did you look at binary diffing projects? Or look at "BinDiff"?
You will find somewhere around 50% (typically, but varies) of the functions in your target executable are not unique.
In other words you will be only be able to match so many functions from one version of the executable to the next updated version. And of course some functions will change that will probably not match up.
A lot of functions, mostly the smaller ones, as the more instructions a function has it is more likely it has to have a unique pattern. 

And is why BinDiff uses function call graph information. It saves the relationship between functions and blocks within a function. Of course can't relate functions if there is no connection. Like C++ class member functions that get accessed only through a pointer.

Sure even if you have a PDB which gives you all that information, it doesn't mean IDA might not mess up the decompilation.
It doesn't mean there won't be functions that blocks that jump around over other functions, etc.
Why I was asking. Trying to figure out which particular functions fail.

For more clarity, when I say "disjointed" function, I mean the the ones that don't have a contiguous body. They have blocks that jump around, but are still considered a function. A good example of ones with many disjointed functions are any of the Windows DLLs. Like if you look at ntdll.dll in IDA you will find that many blocks are shared, function blocks jump all over, etc., because these DLLs are heavily optimized to be as small as possible.

Anyhow the tool wasn't really meant for this. Need to go over at least so many of the problem cases and fix them.
Probably bugs even.
For sure the disjointed type functions are going to be a problem. The idea is to use the signatures for binary scanning. 
To match up the disjointed type, an algorithm that considers function bodies would be needed. In others words would probably need to be inside of a decompiler again where all the information is there as needed.

You need code to detect the disjointed functions and either skip them or see if you can match using only the first function block. Ideally, the other problem cases need to be isolated and fixed. To keep the error rate down.
You should be able in your automation setup, when exception happens, is just skip that function and move on to the next.

**Comment by gurrenm3** [comment]
Gotcha, this helped a lot. I put a try catch around the spot that was breaking and now it's getting through it no problem. I've encountered a new issue though. For some reason there are certain functions that cause ida to freeze and everything stops. Any idea what could be happening here? I think it could be the last hurdle before I'm able to export all of them

**Comment by kweatherman** [comment]
Try commenting out or just removing my custom wait box. Could be a problem.
Also are you creating threads in IDA? It's single threaded, so you can't call most IDA API functions outside of the main thread.
Just a guess though.
Also make a debug build of the plugin, wait for it to freeze up, and then attach VS to debug it. Hard to track but might help figure out where it's stuck from there.

**Comment by gurrenm3** [comment]
Oh those are some good ideas. I'll try them out now. Not multithreaded, I was hoping to do that in the end but looks like thats not possible

**Comment by gurrenm3** [comment]
I tried removing the waitbox but that didn't do anything so I tried debugging with a breakpoint. I held F5 until it got to here and it stopped doing anything. Can't click on IDA either
![image](https://user-images.githubusercontent.com/52727840/225820399-b7847263-d359-4937-b045-6318fdec21e2.png)

**Comment by gurrenm3** [comment]
Here's the same image above but expanded
![image](https://user-images.githubusercontent.com/52727840/225823731-51207079-5d21-41ed-af49-0f066e45f238.png)

**Comment by gurrenm3** [comment]
I've been testing it all morning, currently at function ~60k out of 85k. It hasn't frozen once since the error above

**Comment by kweatherman** [comment]
I reckon I'll close this now. We left this handing out here, and looks like you fixed it.
